#pragma once

#define IDI_ICON1 101

#define AL_ENCODER_VERSION 1, 0, 54
#define AL_ENCODER_VERSION_STR "1,0,54"

#define AL_ENCODER_NAME_PART1 "- AVC "
#define AL_ENCODER_NAME_PART2 "- HEVC "
#define AL_ENCODER_NAME_PART3
#define AL_ENCODER_NAME_PART4
#define AL_ENCODER_NAME_PART5

#define AL_ENCODER_NAME AL_ENCODER_NAME_PART1 AL_ENCODER_NAME_PART2 AL_ENCODER_NAME_PART3 AL_ENCODER_NAME_PART4 AL_ENCODER_NAME_PART5 "-"

#define AL_ENCODER_COMMENTS "Confidential material"
#define AL_ENCODER_COMPANY "Allegro DVT2"
#define AL_ENCODER_PRODUCT_NAME AL_ENCODER_NAME " Encoder Reference Software"
#define AL_ENCODER_FILE_DESCR AL_ENCODER_COMPANY " - " AL_ENCODER_PRODUCT_NAME
#define AL_ENCODER_INTERNAL_NAME AL_ENCODER_NAME " Encoder"
#define AL_ENCODER_COPYRIGHT "Copyright (C) 2019"
#define AL_ENCODER_ORIGINAL_NAME "AL_Encoder.exe"

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 102
#define _APS_NEXT_COMMAND_VALUE 40001
#define _APS_NEXT_CONTROL_VALUE 1001
#define _APS_NEXT_SYMED_VALUE 101
#endif
#endif

