#define IDI_ICON1 101

#define IP_VERSION 1, 0, 37
#define IP_VERSION_STR "1,0,37"

#define IP_ENCODER_NAME_PART1 "AVC/"
#define IP_ENCODER_NAME_PART2 "HEVC"
#define IP_ENCODER_NAME_PART3
#define IP_ENCODER_NAME_PART4
#define IP_ENCODER_NAME IP_ENCODER_NAME_PART1 IP_ENCODER_NAME_PART2 IP_ENCODER_NAME_PART3 IP_ENCODER_NAME_PART4

#define IP_ENCODER_COMMENTS "Confidential material"
#define IP_ENCODER_COMPANY "Allegro DVT2"
#define IP_ENCODER_PRODUCT_NAME IP_ENCODER_NAME " IP Encoder Reference Software"
#define IP_ENCODER_FILE_DESCR IP_ENCODER_COMPANY " - " IP_ENCODER_PRODUCT_NAME
#define IP_ENCODER_INTERNAL_NAME IP_ENCODER_NAME " Encoder"
#define IP_ENCODER_COPYRIGHT "Copyright (C) 2017"
#define IP_ENCODER_ORIGINAL_NAME "AL_Encoder.exe"

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 102
#define _APS_NEXT_COMMAND_VALUE 40001
#define _APS_NEXT_CONTROL_VALUE 1001
#define _APS_NEXT_SYMED_VALUE 101
#endif
#endif

