#define IDI_ICON1 101

#define AL_DECODER_VERSION 1, 0, 43
#define AL_DECODER_VERSION_STR "1,0,43"

#define AL_DECODER_NAME_PART1 "AVC/"
#define AL_DECODER_NAME_PART2 "HEVC"

#define AL_DECODER_NAME AL_DECODER_NAME_PART1 AL_DECODER_NAME_PART2

#define AL_DECODER_COMMENTS "Confidential material"
#define AL_DECODER_COMPANY "Allegro DVT2"
#define AL_DECODER_PRODUCT_NAME AL_DECODER_NAME " Decoder Reference Software"
#define AL_DECODER_FILE_DESCR AL_DECODER_COMPANY " - " AL_DECODER_PRODUCT_NAME
#define AL_DECODER_INTERNAL_NAME AL_DECODER_NAME " Decoder"
#define AL_DECODER_COPYRIGHT "Copyright (C) 2019"
#define AL_DECODER_ORIGINAL_NAME "AL_Decoder.exe"

